### ISSUE TITLE
Question about Without TerminalAPI

### ISSUE THREAD

**Issue by DHStyle541** [Squall4120/StockOverview#1]
Hi, I want to ask, can I make it without TerminalAPI?
because TerminalAPI creates a bug in NewTerminal.

and basically TerminalAPI created a bug for the "terminal scan command".

**Comment by Squall4120** [comment]
Hi, thanks for reaching out! You're absolutely free to modify the StockOverview mod to work without TerminalAPI. The mod is released under the MIT License, so you can adapt it as needed. Just remember to include the original copyright notice and license text in your distribution.

What is the "terminal scan command" bug you mentioned though?
